### ISSUE TITLE
Not an issue or feature request, but now that Classic Shell is discontinued, i'll switch to this soon.

### ISSUE THREAD

**Issue by P4risAndStuff** [AgentMC/power8#32]
Looks like a nice piece of software.

Close this whenever you see it since it pretty much deserves that (it's invalid), I'm basically just expressing my interest.

**Comment by AgentMC** [comment]
Thanks, but just so you know, it's not under _active_ development in scope of new features. Should it crash though I'll try helping.

**Comment by P4risAndStuff** [comment]
Alright, that's fine, thank you for the info 👍
