### ISSUE TITLE
Power8 will not add to custom launch list

### ISSUE THREAD

**Issue by Xoomtell** [AgentMC/power8#33]
Hi

I have just uninstalled Classic Shell and installed Power8 at my desktop PC. It runs nice, so I did do the same on my laptop. It works well on the Laptop as well, but there is one issue. It is not possible to add programs to the custom launch list. I right-click on the program and click "add to custom launch list" bit nothing happens...Any clues.

**Comment by AgentMC** [comment]
Hi
So 1st thing obviously, are you sure you have selected custom launch list from Settings > Most frequently used?

**Comment by Xoomtell** [comment]
Thx - that worked.

**Comment by AgentMC** [comment]
You're welcome.
